#!/usr/bin/env node
/**
 * Generate ~/.acm/mcps-metadata.toml with comprehensive MCP metadata.
 * Sources: mcp_survey.md, user's .mcp.json, popular/known MCP servers.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const TOML = require('smol-toml');

const home = os.homedir();
const outputPath = path.join(home, '.acm', 'mcps-metadata.toml');

// ============================================================================
// Comprehensive MCP Catalog
// ============================================================================
const MCP_DATA = {
  // ---- Browser & Web Automation ----
  '@playwright/mcp': {
    displayName: 'Playwright MCP',
    descriptionJa: 'Webブラウザの自動操作。ページ遷移、クリック、フォーム入力、スクリーンショット、アクセシビリティ解析。AIに「目」と「手」を与える標準MCP。',
    descriptionEn: 'Browser automation for AI agents. Navigate, click, fill forms, screenshot, accessibility tree access.',
    category: 'browser',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@playwright/mcp',
    github: 'microsoft/playwright-mcp',
    popularity: 'high',
    tags: ['browser', 'automation', 'testing', 'screenshot', 'accessibility'],
  },
  'chrome-devtools-mcp': {
    displayName: 'Chrome DevTools MCP',
    descriptionJa: 'Chrome DevToolsの全機能をAIから利用。ネットワーク監視、コンソール、パフォーマンス計測、メモリプロファイリング、Lighthouse監査。',
    descriptionEn: 'Full Chrome DevTools access for AI agents. Network, console, performance, memory, Lighthouse.',
    category: 'browser',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'chrome-devtools-mcp',
    github: 'anthropic/chrome-devtools-mcp',
    popularity: 'high',
    tags: ['chrome', 'devtools', 'debugging', 'performance', 'testing', 'lighthouse'],
  },
  'browserbase-mcp': {
    displayName: 'Browserbase MCP',
    descriptionJa: 'クラウドブラウザを使ったWeb自動化。ステージング環境でのE2Eテスト、データ抽出、セッション記録。',
    descriptionEn: 'Cloud browser automation for staging E2E tests, data extraction, and session recording.',
    category: 'browser',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@browserbasehq/stagehand-mcp',
    github: 'browserbase/mcp-server',
    popularity: 'medium',
    tags: ['browser', 'cloud', 'e2e-testing', 'scraping'],
  },

  // ---- Search & Information Retrieval ----
  '@modelcontextprotocol/server-brave-search': {
    displayName: 'Brave Search MCP',
    descriptionJa: 'Brave Search APIを使ったWeb検索とローカル検索。プライバシー重視の検索エンジンをAIから直接利用。',
    descriptionEn: 'Web and local search via Brave Search API. Privacy-focused search for AI agents.',
    category: 'search',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-brave-search',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['search', 'web', 'local-search', 'brave'],
  },
  'server-perplexity-ask': {
    displayName: 'Perplexity Ask MCP',
    descriptionJa: 'Perplexity AIのリサーチ機能を使った深掘り検索。最新情報を含む包括的な回答を生成。',
    descriptionEn: 'Deep research via Perplexity AI. Comprehensive answers with up-to-date information.',
    category: 'search',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'server-perplexity-ask',
    popularity: 'high',
    tags: ['search', 'research', 'perplexity', 'ai'],
  },
  '@upstash/context7-mcp': {
    displayName: 'Context7 MCP',
    descriptionJa: '最新のライブラリ・フレームワークドキュメントを取得。パッケージのAPI仕様やサンプルコードを提供。',
    descriptionEn: 'Up-to-date library/framework documentation. API specs and code examples.',
    category: 'search',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@upstash/context7-mcp',
    popularity: 'high',
    tags: ['documentation', 'library', 'api', 'code-examples'],
  },
  'deepwiki': {
    displayName: 'DeepWiki MCP',
    descriptionJa: 'GitHubリポジトリのAIドキュメント生成と検索。コードベース全体を理解し質問に回答。',
    descriptionEn: 'AI-powered GitHub repo documentation and Q&A. Understand entire codebases.',
    category: 'search',
    language: 'TypeScript',
    transport: 'http',
    website: 'https://mcp.deepwiki.com/mcp',
    popularity: 'medium',
    tags: ['documentation', 'github', 'code-analysis', 'wiki'],
  },
  'exa-mcp': {
    displayName: 'Exa MCP',
    descriptionJa: 'AIネイティブなWeb検索API。コンテンツベースの検索で高精度な情報取得。',
    descriptionEn: 'AI-native web search API. Content-based semantic search for precise results.',
    category: 'search',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@anthropic/exa-mcp-server',
    popularity: 'medium',
    tags: ['search', 'semantic-search', 'web'],
  },
  'tavily-mcp': {
    displayName: 'Tavily Search MCP',
    descriptionJa: 'AIエージェント専用のリアルタイムWeb検索API。検索結果の要約・抽出に最適化。',
    descriptionEn: 'Real-time web search API built for AI agents. Optimized for summarization and extraction.',
    category: 'search',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'tavily-mcp',
    popularity: 'medium',
    tags: ['search', 'real-time', 'summarization'],
  },

  // ---- Development & Code ----
  '@modelcontextprotocol/server-github': {
    displayName: 'GitHub MCP',
    descriptionJa: 'GitHub APIを通じたリポジトリ管理。PR作成、Issue管理、コード検索、ファイル操作を自然言語で実行。',
    descriptionEn: 'GitHub API integration. Create PRs, manage issues, search code, manipulate files via natural language.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-github',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['github', 'git', 'pull-request', 'issue', 'code-search'],
  },
  'git-mcp-server': {
    displayName: 'Git MCP',
    descriptionJa: 'ローカルGit操作。ブランチ作成、コミット、プッシュ、プル、マージ、ステータス確認。',
    descriptionEn: 'Local Git operations. Branch, commit, push, pull, merge, status.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'git-mcp-server',
    popularity: 'medium',
    tags: ['git', 'version-control', 'commit', 'branch'],
  },
  '@anthropic/xcodebuild-mcp': {
    displayName: 'XcodeBuild MCP',
    descriptionJa: 'Xcodeプロジェクトのビルド・テスト・実行。iOS/Macアプリ開発の自動化。シミュレーター制御、エラー診断。',
    descriptionEn: 'Build, test, and run Xcode projects. iOS/Mac app development automation. Simulator control, error diagnosis.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'xcodebuildmcp',
    github: 'anthropic/xcodebuild-mcp',
    popularity: 'medium',
    tags: ['xcode', 'ios', 'macos', 'swift', 'build', 'testing'],
  },
  'mcp-py-repl': {
    displayName: 'Python REPL MCP',
    descriptionJa: 'サンドボックス内でPythonコードを安全に実行。データ分析、プロトタイピング、計算処理に最適。',
    descriptionEn: 'Safe Python code execution in sandbox. Data analysis, prototyping, computation.',
    category: 'development',
    language: 'Python',
    transport: 'stdio',
    popularity: 'low',
    tags: ['python', 'repl', 'sandbox', 'execution'],
  },
  'node-repl-mcp': {
    displayName: 'Node REPL MCP',
    descriptionJa: 'Node.jsのREPL環境を提供。JavaScript/TypeScriptコードの実行とテスト。',
    descriptionEn: 'Node.js REPL environment. Execute and test JavaScript/TypeScript code.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['nodejs', 'repl', 'javascript', 'execution'],
  },
  'codetree-mcp': {
    displayName: 'CodeTree MCP',
    descriptionJa: 'コードベースの構造的理解。AST解析による関数・クラス・依存関係のマッピング。',
    descriptionEn: 'Structural code understanding via AST analysis. Function, class, and dependency mapping.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['ast', 'code-analysis', 'structure', 'refactoring'],
  },
  'sentry-mcp': {
    displayName: 'Sentry MCP',
    descriptionJa: 'Sentryのエラー監視データにアクセス。スタックトレース分析、エラー頻度の確認、修正提案。',
    descriptionEn: 'Access Sentry error monitoring data. Stack trace analysis, error frequency, fix suggestions.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@sentry/mcp',
    popularity: 'medium',
    tags: ['sentry', 'error-monitoring', 'debugging', 'observability'],
  },
  'coderabbit-mcp': {
    displayName: 'CodeRabbit MCP',
    descriptionJa: 'AIコードレビュー。PRの自動レビュー、バグ検出、改善提案。',
    descriptionEn: 'AI code review. Automated PR review, bug detection, improvement suggestions.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['code-review', 'pull-request', 'automation'],
  },

  // ---- Database & Data ----
  '@modelcontextprotocol/server-postgres': {
    displayName: 'PostgreSQL MCP',
    descriptionJa: 'PostgreSQLデータベース接続。スキーマ読み取り、SQL自動生成・実行、データ分析。',
    descriptionEn: 'PostgreSQL database connection. Schema reading, SQL auto-generation/execution, data analysis.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-postgres',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['postgres', 'sql', 'database', 'analytics'],
  },
  '@anthropic/motherduck-mcp': {
    displayName: 'MotherDuck MCP',
    descriptionJa: 'MotherDuck/DuckDBクラウドデータウェアハウスへの接続。高速分析クエリの実行。',
    descriptionEn: 'MotherDuck/DuckDB cloud data warehouse connection. Fast analytical queries.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['duckdb', 'motherduck', 'data-warehouse', 'analytics'],
  },
  '@modelcontextprotocol/server-sqlite': {
    displayName: 'SQLite MCP',
    descriptionJa: 'SQLiteデータベースの操作。ローカルDBの作成、クエリ、マイグレーション。',
    descriptionEn: 'SQLite database operations. Local DB creation, querying, migration.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-sqlite',
    github: 'modelcontextprotocol/servers',
    popularity: 'medium',
    tags: ['sqlite', 'database', 'local', 'embedded'],
  },
  'neon-mcp': {
    displayName: 'Neon MCP',
    descriptionJa: 'NeonサーバーレスPostgreSQL。ブランチ作成、データベース管理、接続文字列の取得。',
    descriptionEn: 'Neon serverless PostgreSQL. Branch creation, database management, connection strings.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@neondatabase/mcp',
    popularity: 'medium',
    tags: ['neon', 'postgres', 'serverless', 'branching'],
  },
  'supabase-mcp': {
    displayName: 'Supabase MCP',
    descriptionJa: 'Supabaseバックエンド管理。データベース、認証、ストレージ、Edge Functionsの操作。',
    descriptionEn: 'Supabase backend management. Database, auth, storage, Edge Functions.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['supabase', 'database', 'authentication', 'storage', 'backend'],
  },
  'clickhouse-mcp': {
    displayName: 'ClickHouse MCP',
    descriptionJa: 'ClickHouseカラム型データベースへの接続。高速分析クエリ、リアルタイムデータ処理。',
    descriptionEn: 'ClickHouse columnar database connection. Fast analytical queries, real-time processing.',
    category: 'database',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['clickhouse', 'analytics', 'real-time', 'olap'],
  },

  // ---- Cloud & Infrastructure ----
  'terraform-mcp': {
    displayName: 'Terraform MCP',
    descriptionJa: 'HashiCorp Terraformによるインフラ管理。IaCコードの生成、plan/applyの実行、状態確認。',
    descriptionEn: 'Infrastructure management via HashiCorp Terraform. IaC generation, plan/apply, state inspection.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['terraform', 'iac', 'infrastructure', 'hashicorp'],
  },
  'docker-mcp': {
    displayName: 'Docker MCP',
    descriptionJa: 'Dockerコンテナ管理。イメージビルド、コンテナ起動・停止、ログ確認、Compose操作。',
    descriptionEn: 'Docker container management. Image build, container start/stop, logs, Compose operations.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['docker', 'container', 'compose', 'devops'],
  },
  'kubernetes-mcp': {
    displayName: 'Kubernetes MCP',
    descriptionJa: 'Kubernetesクラスタの管理。Pod操作、デプロイ、スケーリング、トラブルシューティング。',
    descriptionEn: 'Kubernetes cluster management. Pod operations, deployment, scaling, troubleshooting.',
    category: 'infrastructure',
    language: 'Go',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['kubernetes', 'k8s', 'container', 'orchestration', 'devops'],
  },
  'vercel-mcp': {
    displayName: 'Vercel MCP',
    descriptionJa: 'Vercelプラットフォームの管理。デプロイ、ドメイン設定、環境変数、プロジェクト設定。',
    descriptionEn: 'Vercel platform management. Deployments, domains, environment variables, project settings.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['vercel', 'deployment', 'hosting', 'serverless'],
  },
  'cloudflare-mcp': {
    displayName: 'Cloudflare MCP',
    descriptionJa: 'Cloudflare Workers/Pages/D1/R2の管理。デプロイ、KVストア操作、DNS設定。',
    descriptionEn: 'Cloudflare Workers/Pages/D1/R2 management. Deploy, KV store operations, DNS settings.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['cloudflare', 'workers', 'edge', 'deployment'],
  },
  'datadog-mcp': {
    displayName: 'Datadog MCP',
    descriptionJa: 'Datadogの監視データにアクセス。メトリクス、ログ、APM、アラートの確認と分析。',
    descriptionEn: 'Datadog monitoring data access. Metrics, logs, APM, alert inspection and analysis.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['datadog', 'monitoring', 'observability', 'metrics', 'logging'],
  },
  'prometheus-mcp': {
    displayName: 'Prometheus MCP',
    descriptionJa: 'Prometheusメトリクスのクエリと分析。PromQLによるモニタリングデータの可視化と異常検知。',
    descriptionEn: 'Prometheus metrics querying and analysis. PromQL-based visualization and anomaly detection.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['prometheus', 'metrics', 'monitoring', 'promql'],
  },
  'daytona-mcp': {
    displayName: 'Daytona MCP',
    descriptionJa: 'セキュアな開発環境のプロビジョニング。隔離されたサンドボックスでのコード実行とテスト。',
    descriptionEn: 'Secure dev environment provisioning. Isolated sandbox code execution and testing.',
    category: 'infrastructure',
    language: 'Go',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['sandbox', 'dev-environment', 'security', 'isolation'],
  },

  // ---- Communication & Productivity ----
  'slack-mcp': {
    displayName: 'Slack MCP',
    descriptionJa: 'Slackワークスペースの操作。メッセージ送信、チャンネル管理、検索、ユーザー情報取得。',
    descriptionEn: 'Slack workspace operations. Message sending, channel management, search, user info.',
    category: 'communication',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-slack',
    popularity: 'high',
    tags: ['slack', 'messaging', 'communication', 'team'],
  },
  '@modelcontextprotocol/server-google-workspace': {
    displayName: 'Google Workspace MCP',
    descriptionJa: 'Google Workspaceの統合操作。Gmail、Calendar、Drive、Docs、SheetsをAIから制御。',
    descriptionEn: 'Google Workspace integration. Gmail, Calendar, Drive, Docs, Sheets from AI.',
    category: 'communication',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['google', 'gmail', 'calendar', 'drive', 'workspace'],
  },
  'notion-mcp': {
    displayName: 'Notion MCP',
    descriptionJa: 'Notionワークスペースの操作。ページ作成、データベース検索、コンテンツ管理。',
    descriptionEn: 'Notion workspace operations. Page creation, database search, content management.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['notion', 'documentation', 'wiki', 'knowledge-base'],
  },
  'linear-mcp': {
    displayName: 'Linear MCP',
    descriptionJa: 'Linearプロジェクト管理。Issue作成、スプリント管理、チームワークフローの自動化。',
    descriptionEn: 'Linear project management. Issue creation, sprint management, team workflow automation.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['linear', 'project-management', 'issue', 'sprint'],
  },
  'zapier-mcp': {
    displayName: 'Zapier MCP',
    descriptionJa: '7,000以上のアプリ連携。Slack送信、カレンダー登録、メール送信などの自動化ワークフロー。',
    descriptionEn: '7,000+ app integrations. Automation workflows for Slack, calendar, email, etc.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'high',
    tags: ['zapier', 'automation', 'integration', 'workflow'],
  },

  // ---- Design & Creative ----
  'figma-mcp': {
    displayName: 'Figma MCP',
    descriptionJa: 'Figmaデザインファイルの読み取りと操作。コンポーネント情報、スタイル抽出、デザイン→コード変換。',
    descriptionEn: 'Figma design file reading and manipulation. Component info, style extraction, design-to-code.',
    category: 'design',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'high',
    tags: ['figma', 'design', 'ui', 'design-to-code'],
  },
  'blender-mcp': {
    displayName: 'Blender MCP',
    descriptionJa: 'Blender 3Dモデリングソフトの操作。オブジェクト作成、マテリアル設定、レンダリング制御。',
    descriptionEn: 'Blender 3D modeling control. Object creation, material setup, rendering control.',
    category: 'design',
    language: 'Python',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['blender', '3d', 'modeling', 'rendering'],
  },
  'excalidraw-mcp': {
    displayName: 'Excalidraw MCP',
    descriptionJa: '手書き風の図やイラストを作成。フローチャート、マインドマップ、アーキテクチャ図の生成。',
    descriptionEn: 'Hand-drawn style diagrams and illustrations. Flowcharts, mind maps, architecture diagrams.',
    category: 'design',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['excalidraw', 'diagram', 'drawing', 'visualization'],
  },
  'canva-mcp': {
    displayName: 'Canva MCP',
    descriptionJa: 'Canvaデザインプラットフォームの操作。テンプレート検索、デザイン作成・編集、ブランド管理。',
    descriptionEn: 'Canva design platform operations. Template search, design creation/editing, brand management.',
    category: 'design',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['canva', 'design', 'template', 'brand'],
  },
  'remotion-mcp': {
    displayName: 'Remotion MCP',
    descriptionJa: 'Reactベースの動画生成。プログラムによるアニメーション動画の作成と編集。',
    descriptionEn: 'React-based video generation. Programmatic animation video creation and editing.',
    category: 'design',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['remotion', 'video', 'react', 'animation'],
  },

  // ---- AI & Thinking ----
  '@modelcontextprotocol/server-sequential-thinking': {
    displayName: 'Sequential Thinking MCP',
    descriptionJa: '構造化された思考プロセスの制御。複雑な問題を段階的に分析・解決するためのフレームワーク。',
    descriptionEn: 'Structured thinking process control. Framework for step-by-step analysis and problem solving.',
    category: 'ai-tool',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-sequential-thinking',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['thinking', 'reasoning', 'problem-solving', 'analysis'],
  },
  '@modelcontextprotocol/server-memory': {
    displayName: 'Knowledge Graph Memory MCP',
    descriptionJa: '永続的な知識グラフメモリ。会話の文脈やユーザー情報をグラフ構造で記憶・検索。',
    descriptionEn: 'Persistent knowledge graph memory. Store and search conversation context and user info as graph.',
    category: 'ai-tool',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-memory',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['memory', 'knowledge-graph', 'context', 'persistence'],
  },
  'superpowers-mcp': {
    displayName: 'Superpowers MCP',
    descriptionJa: 'AIエージェントの能力拡張キット。並列処理、プラン実行、コードレビュー対応、ブレインストーミング。',
    descriptionEn: 'AI agent capability extension kit. Parallel processing, plan execution, code review, brainstorming.',
    category: 'ai-tool',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['agent', 'orchestration', 'parallel', 'workflow'],
  },
  'metamcp': {
    displayName: 'MetaMCP',
    descriptionJa: '複数MCPサーバーを統合管理するメタレイヤー。MCP間の連携とオーケストレーション。',
    descriptionEn: 'Meta-layer for unified management of multiple MCP servers. Inter-MCP coordination and orchestration.',
    category: 'ai-tool',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['meta', 'orchestration', 'management', 'integration'],
  },

  // ---- File System & OS ----
  '@modelcontextprotocol/server-filesystem': {
    displayName: 'Filesystem MCP',
    descriptionJa: 'ファイルシステム操作。読み書き、ディレクトリ操作、ファイル検索、メタデータ取得。',
    descriptionEn: 'Filesystem operations. Read/write, directory operations, file search, metadata.',
    category: 'system',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@modelcontextprotocol/server-filesystem',
    github: 'modelcontextprotocol/servers',
    popularity: 'high',
    tags: ['filesystem', 'file', 'directory', 'storage'],
  },
  'mac-agent': {
    displayName: 'Mac Agent MCP',
    descriptionJa: 'macOSのシステム操作。アプリ起動、ファイル管理、クリップボード、AppleScript実行。',
    descriptionEn: 'macOS system operations. App launch, file management, clipboard, AppleScript execution.',
    category: 'system',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['macos', 'system', 'automation', 'applescript'],
  },

  // ---- Academic & Research ----
  'arxiv-mcp': {
    displayName: 'arXiv MCP',
    descriptionJa: 'arXivの学術論文検索と取得。論文のメタデータ、要約、PDFダウンロード。',
    descriptionEn: 'arXiv academic paper search and retrieval. Metadata, abstracts, PDF downloads.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['arxiv', 'paper', 'research', 'academic', 'preprint'],
  },
  'semantic-scholar-mcp': {
    displayName: 'Semantic Scholar MCP',
    descriptionJa: 'Semantic Scholarの学術文献検索。引用情報、関連論文、著者情報の取得。',
    descriptionEn: 'Semantic Scholar academic literature search. Citations, related papers, author info.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['semantic-scholar', 'paper', 'citation', 'research'],
  },
  'crossref-mcp': {
    displayName: 'Crossref MCP',
    descriptionJa: 'Crossref APIを使った学術DOI・メタデータ検索。論文情報、引用関係の取得。',
    descriptionEn: 'Academic DOI/metadata search via Crossref API. Paper info, citation relationships.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['crossref', 'doi', 'metadata', 'citation'],
  },
  'openalex-mcp': {
    displayName: 'OpenAlex MCP',
    descriptionJa: 'OpenAlexのオープン学術データ検索。論文、著者、機関、トピックの包括的検索。',
    descriptionEn: 'OpenAlex open academic data search. Comprehensive paper, author, institution, topic search.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['openalex', 'open-access', 'research', 'bibliometrics'],
  },
  'zotero-mcp': {
    displayName: 'Zotero MCP',
    descriptionJa: 'Zotero文献管理。論文の追加・整理・検索、コレクション管理、引用生成。',
    descriptionEn: 'Zotero reference management. Add, organize, search papers, collection management, citation generation.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'zotero-mcp',
    popularity: 'medium',
    tags: ['zotero', 'reference', 'bibliography', 'citation', 'paper'],
  },
  'doi-mcp': {
    displayName: 'DOI MCP',
    descriptionJa: 'DOI解決と学術メタデータ取得。論文の書誌情報、アブストラクト、出版情報をDOIから取得。',
    descriptionEn: 'DOI resolution and academic metadata retrieval. Bibliographic info, abstracts from DOIs.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['doi', 'metadata', 'reference', 'paper'],
  },
  'mcp-refchecker': {
    displayName: 'Reference Checker MCP',
    descriptionJa: '学術論文の参考文献検証。引用の整合性チェック、DOI検証、フォーマット確認。',
    descriptionEn: 'Academic reference validation. Citation consistency check, DOI verification, format check.',
    category: 'academic',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['reference', 'validation', 'citation', 'doi'],
  },

  // ---- Note-taking & Knowledge ----
  'mcp-obsidian': {
    displayName: 'Obsidian MCP',
    descriptionJa: 'Obsidianノートの操作。ノート作成・編集・検索、リンク管理、プラグイン連携。',
    descriptionEn: 'Obsidian note operations. Note creation/editing/search, link management, plugin integration.',
    category: 'knowledge',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'mcp-obsidian',
    popularity: 'medium',
    tags: ['obsidian', 'note', 'markdown', 'knowledge-base'],
  },
  '@yama662607/obsidian-companion-mcp': {
    displayName: 'Obsidian Companion MCP',
    descriptionJa: 'Obsidianの拡張操作。AIによるノート作成支援、タグ提案、リンク補完、コンテンツ生成。',
    descriptionEn: 'Extended Obsidian operations. AI-assisted note creation, tag suggestions, link completion.',
    category: 'knowledge',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@yama662607/obsidian-companion-mcp',
    popularity: 'low',
    tags: ['obsidian', 'companion', 'ai', 'note'],
  },
  '@yama662607/obsidian-excalidraw-mcp': {
    displayName: 'Obsidian Excalidraw MCP',
    descriptionJa: 'Obsidian内のExcalidraw図の操作。図の作成・編集・検索、Obsidianノートとの連携。',
    descriptionEn: 'Excalidraw diagram operations within Obsidian. Diagram create/edit/search, note integration.',
    category: 'knowledge',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@yama662607/obsidian-excalidraw-mcp',
    popularity: 'low',
    tags: ['obsidian', 'excalidraw', 'diagram', 'drawing'],
  },
  '@yama662607/anki-mcp': {
    displayName: 'Anki MCP',
    descriptionJa: 'Anki暗記カードの作成と管理。デッキ操作、カード生成、学習進捗の確認。',
    descriptionEn: 'Anki flashcard creation and management. Deck operations, card generation, learning progress.',
    category: 'knowledge',
    language: 'TypeScript',
    transport: 'stdio',
    package: '@yama662607/anki-mcp',
    popularity: 'low',
    tags: ['anki', 'flashcard', 'learning', 'spaced-repetition'],
  },
  'apple-notes-mcp': {
    displayName: 'Apple Notes MCP',
    descriptionJa: 'macOSのApple Notes連携。ノート作成・検索・編集、フォルダ管理。',
    descriptionEn: 'macOS Apple Notes integration. Note creation/search/edit, folder management.',
    category: 'knowledge',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['apple-notes', 'macos', 'note', 'icloud'],
  },

  // ---- Finance & Business ----
  'finmcp': {
    displayName: 'FinMCP',
    descriptionJa: '金融データの統合アクセス。企業財務、市場データ、経済指標の検索と分析。',
    descriptionEn: 'Integrated financial data access. Corporate finance, market data, economic indicators.',
    category: 'finance',
    language: 'Python',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['finance', 'market-data', 'economy', 'analysis'],
  },
  'stripe-mcp': {
    displayName: 'Stripe MCP',
    descriptionJa: 'Stripe決済プラットフォームの操作。顧客管理、サブスクリプション、支払い処理、分析。',
    descriptionEn: 'Stripe payment platform operations. Customer management, subscriptions, payment processing.',
    category: 'finance',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['stripe', 'payment', 'subscription', 'billing'],
  },
  'solana-agent-kit': {
    displayName: 'Solana Agent Kit MCP',
    descriptionJa: 'Solanaブロックチェーンの操作。ウォレット管理、トークン操作、トランザクション実行。',
    descriptionEn: 'Solana blockchain operations. Wallet management, token operations, transaction execution.',
    category: 'finance',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['solana', 'blockchain', 'crypto', 'wallet'],
  },

  // ---- IoT & Hardware ----
  'home-assistant-mcp': {
    displayName: 'Home Assistant MCP',
    descriptionJa: 'Home Assistantのスマートホーム制御。デバイス操作、オートメーション、状態監視。',
    descriptionEn: 'Home Assistant smart home control. Device operations, automation, state monitoring.',
    category: 'hardware',
    language: 'Python',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['home-assistant', 'iot', 'smart-home', 'automation'],
  },
  'arduino-mcp': {
    displayName: 'Arduino MCP',
    descriptionJa: 'Arduinoマイコンの開発支援。コード生成、コンパイル、アップロード、シリアル通信。',
    descriptionEn: 'Arduino microcontroller development. Code generation, compilation, upload, serial communication.',
    category: 'hardware',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['arduino', 'iot', 'microcontroller', 'embedded'],
  },
  'esp32-mcp': {
    displayName: 'ESP32 MCP',
    descriptionJa: 'ESP32マイコンの開発と管理。WiFi/Bluetooth設定、センサーデータ取得、OTA更新。',
    descriptionEn: 'ESP32 microcontroller development and management. WiFi/Bluetooth, sensor data, OTA updates.',
    category: 'hardware',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['esp32', 'iot', 'wifi', 'bluetooth', 'embedded'],
  },

  // ---- Game Development ----
  'unity-mcp': {
    displayName: 'Unity MCP',
    descriptionJa: 'Unityゲームエンジンの操作。シーン管理、アセット操作、スクリプト編集、ビルド実行。',
    descriptionEn: 'Unity game engine operations. Scene management, asset operations, script editing, builds.',
    category: 'gamedev',
    language: 'C#',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['unity', 'gamedev', '3d', 'csharp'],
  },
  'unreal-mcp': {
    displayName: 'Unreal Engine MCP',
    descriptionJa: 'Unreal Engineの操作。ブループリント、アセット管理、レベル編集、レンダリング制御。',
    descriptionEn: 'Unreal Engine operations. Blueprints, asset management, level editing, rendering control.',
    category: 'gamedev',
    language: 'C++',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['unreal', 'gamedev', '3d', 'blueprint'],
  },

  // ---- Security ----
  'cyntrisec-mcp': {
    displayName: 'Cyntrisec MCP',
    descriptionJa: 'AWSセキュリティグラフ分析。IAM設定、ネットワーク経路、脆弱性の可視化と分析。',
    descriptionEn: 'AWS security graph analysis. IAM, network paths, vulnerability visualization and analysis.',
    category: 'security',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['aws', 'security', 'iam', 'network', 'compliance'],
  },

  // ---- Other Specialized MCPs ----
  'typst-mcp': {
    displayName: 'Typst MCP',
    descriptionJa: 'Typst組版システムのコンパイルと操作。学術論文・レポートの自動組版。',
    descriptionEn: 'Typst typesetting system compilation and operations. Academic paper/report auto-typesetting.',
    category: 'academic',
    language: 'Python',
    transport: 'stdio',
    popularity: 'low',
    tags: ['typst', 'typesetting', 'latex', 'paper', 'document'],
  },
  'jupyter-mcp': {
    displayName: 'Jupyter MCP',
    descriptionJa: 'Jupyter Notebookの操作。セル作成・実行、ノートブック管理、データ可視化。',
    descriptionEn: 'Jupyter Notebook operations. Cell creation/execution, notebook management, data visualization.',
    category: 'development',
    language: 'Python',
    transport: 'stdio',
    popularity: 'low',
    tags: ['jupyter', 'notebook', 'python', 'data-science'],
  },
  'fusion360-mcp': {
    displayName: 'Fusion 360 MCP',
    descriptionJa: 'Autodesk Fusion 360のCAD操作。3Dモデリング、パラメトリック設計、アセンブリ管理。',
    descriptionEn: 'Autodesk Fusion 360 CAD operations. 3D modeling, parametric design, assembly management.',
    category: 'design',
    language: 'Python',
    transport: 'stdio',
    popularity: 'low',
    tags: ['fusion360', 'cad', '3d-modeling', 'mechanical'],
  },
  'serena-mcp': {
    displayName: 'Serena MCP',
    descriptionJa: 'コードベースの意味理解と編集。シンボル検索、リファクタリング支援、コードナビゲーション。',
    descriptionEn: 'Semantic code understanding and editing. Symbol search, refactoring assistance, code navigation.',
    category: 'development',
    language: 'Python',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['code-analysis', 'refactoring', 'lsp', 'navigation'],
  },
  'heygen-mcp': {
    displayName: 'HeyGen MCP',
    descriptionJa: 'AIアバター動画生成。テキストからの動画作成、アバターカスタマイズ、多言語対応。',
    descriptionEn: 'AI avatar video generation. Text-to-video, avatar customization, multi-language.',
    category: 'design',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['video', 'avatar', 'ai-generation', 'heygen'],
  },

  // ---- Plugin-discovered MCPs ----
  'asana': {
    displayName: 'Asana MCP',
    descriptionJa: 'Asanaプロジェクト管理。タスク作成・更新・検索、プロジェクト管理、チームコラボレーション。',
    descriptionEn: 'Asana project management. Task create/update/search, project management, team collaboration.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['asana', 'project-management', 'task', 'team'],
  },
  'cloudflare-api': {
    displayName: 'Cloudflare API MCP',
    descriptionJa: 'Cloudflare APIの統合アクセス。Workers、Pages、DNS、セキュリティ設定の管理。',
    descriptionEn: 'Unified Cloudflare API access. Manage Workers, Pages, DNS, and security settings.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'http',
    website: 'https://mcp.cloudflare.com/mcp',
    popularity: 'medium',
    tags: ['cloudflare', 'api', 'workers', 'dns'],
  },
  'discord': {
    displayName: 'Discord MCP',
    descriptionJa: 'Discordサーバー・チャンネルの操作。メッセージ送信、チャンネル管理、ユーザー情報取得。',
    descriptionEn: 'Discord server/channel operations. Message posting, channel management, user info.',
    category: 'communication',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['discord', 'messaging', 'chat', 'community'],
  },
  'firebase': {
    displayName: 'Firebase MCP',
    descriptionJa: 'Firebaseプラットフォームの管理。Firestore、Authentication、Hosting、Cloud Functions。',
    descriptionEn: 'Firebase platform management. Firestore, Authentication, Hosting, Cloud Functions.',
    category: 'infrastructure',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['firebase', 'google', 'firestore', 'authentication', 'hosting'],
  },
  'gitlab': {
    displayName: 'GitLab MCP',
    descriptionJa: 'GitLab APIを通じたリポジトリ管理。MR作成、Issue管理、CI/CDパイプライン操作。',
    descriptionEn: 'GitLab API integration. MR creation, issue management, CI/CD pipeline operations.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['gitlab', 'git', 'merge-request', 'ci-cd'],
  },
  'greptile': {
    displayName: 'Greptile MCP',
    descriptionJa: 'コードベースのAI検索・理解。リポジトリ全体を横断した意味検索とコードQA。',
    descriptionEn: 'AI-powered codebase search and understanding. Semantic search and code QA across repos.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['code-search', 'semantic', 'code-analysis', 'qa'],
  },
  'imessage': {
    displayName: 'iMessage MCP',
    descriptionJa: 'macOSのiMessage/Messages連携。メッセージ送信、会話検索、連絡先管理。',
    descriptionEn: 'macOS iMessage/Messages integration. Message sending, conversation search, contact management.',
    category: 'communication',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'low',
    tags: ['imessage', 'macos', 'messaging', 'apple'],
  },
  'laravel-boost': {
    displayName: 'Laravel Boost MCP',
    descriptionJa: 'Laravelフレームワーク開発支援。コード生成、マイグレーション、Artisanコマンド実行。',
    descriptionEn: 'Laravel framework development support. Code generation, migrations, Artisan commands.',
    category: 'development',
    language: 'PHP',
    transport: 'stdio',
    popularity: 'low',
    tags: ['laravel', 'php', 'framework', 'code-generation'],
  },
  'linear': {
    displayName: 'Linear MCP',
    descriptionJa: 'Linearプロジェクト管理。Issue作成、スプリント管理、チームワークフローの自動化。',
    descriptionEn: 'Linear project management. Issue creation, sprint management, team workflow automation.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'http',
    website: 'https://mcp.linear.app/mcp',
    popularity: 'medium',
    tags: ['linear', 'project-management', 'issue', 'sprint'],
  },
  'notion': {
    displayName: 'Notion MCP',
    descriptionJa: 'Notionワークスペースの操作。ページ作成、データベース検索、コンテンツ管理。',
    descriptionEn: 'Notion workspace operations. Page creation, database search, content management.',
    category: 'productivity',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['notion', 'documentation', 'wiki', 'knowledge-base'],
  },
  'telegram': {
    displayName: 'Telegram MCP',
    descriptionJa: 'Telegramメッセージング。ボット作成、メッセージ送信、チャンネル管理。',
    descriptionEn: 'Telegram messaging. Bot creation, message sending, channel management.',
    category: 'communication',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['telegram', 'messaging', 'bot', 'chat'],
  },
  'xcodebuildmcp': {
    displayName: 'XcodeBuild MCP',
    descriptionJa: 'Xcodeプロジェクトのビルド・テスト・実行。iOS/Macアプリ開発の自動化。シミュレーター制御、UIテスト、エラー診断。',
    descriptionEn: 'Xcode project build/test/run. iOS/Mac app development automation. Simulator control, UI testing, error diagnosis.',
    category: 'development',
    language: 'TypeScript',
    transport: 'stdio',
    package: 'xcodebuildmcp',
    github: 'anthropic/xcodebuild-mcp',
    popularity: 'medium',
    tags: ['xcode', 'ios', 'macos', 'swift', 'build', 'testing', 'simulator'],
  },
  'computer-use': {
    displayName: 'Computer Use MCP',
    descriptionJa: 'コンピュータ操作の自動化。画面認識、マウス・キーボード操作、アプリケーション制御。',
    descriptionEn: 'Computer use automation. Screen recognition, mouse/keyboard control, application control.',
    category: 'ai-tool',
    language: 'TypeScript',
    transport: 'stdio',
    popularity: 'medium',
    tags: ['computer-use', 'automation', 'screen', 'desktop'],
  },
};

// ============================================================================
// Main
// ============================================================================

function main() {
  const now = new Date().toISOString();
  const output = { version: '1.0', mcps: {} };

  for (const [id, data] of Object.entries(MCP_DATA)) {
    output.mcps[id] = {
      displayName: data.displayName,
      descriptionJa: data.descriptionJa,
      descriptionEn: data.descriptionEn,
      category: data.category,
      language: data.language,
      transport: data.transport,
      package: data.package || undefined,
      github: data.github || undefined,
      website: data.website || undefined,
      popularity: data.popularity,
      sourceType: data.sourceType,
      agent: data.agent,
      addedAt: now,
      pinned: undefined,
      deprecated: undefined,
      tags: data.tags,
    };
  }

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outputPath, TOML.stringify(output), 'utf8');

  // Report
  const cats = {};
  const langs = {};
  const pops = {};
  let totalTags = 0;
  const tagCounts = {};

  for (const [id, data] of Object.entries(MCP_DATA)) {
    cats[data.category] = (cats[data.category] || 0) + 1;
    langs[data.language] = (langs[data.language] || 0) + 1;
    pops[data.popularity] = (pops[data.popularity] || 0) + 1;
    for (const t of data.tags) {
      tagCounts[t] = (tagCounts[t] || 0) + 1;
      totalTags++;
    }
  }

  console.log(`Total MCPs: ${Object.keys(MCP_DATA).length}`);
  console.log(`Total tags: ${totalTags}`);
  console.log(`Unique tags: ${Object.keys(tagCounts).length}`);
  console.log(`\nCategory distribution:`);
  Object.entries(cats).sort((a,b) => b[1]-a[1]).forEach(([c,n]) => console.log(`  ${c}: ${n}`));
  console.log(`\nLanguage distribution:`);
  Object.entries(langs).sort((a,b) => b[1]-a[1]).forEach(([l,n]) => console.log(`  ${l}: ${n}`));
  console.log(`\nPopularity:`);
  Object.entries(pops).sort((a,b) => b[1]-a[1]).forEach(([p,n]) => console.log(`  ${p}: ${n}`));
  console.log(`\nWritten to: ${outputPath}`);
}

main();
